Repository lumiastream/lumia-translations, pull requests merged in 2024-12, with the labels that each got.

#1 chore: update regex label for folder watch
  package-lock.json
  src/translations/en.translations.json
Labels: chore

#3 Fix/cleanup translations
  src/translations/ar.translations.json
  src/translations/de.translations.json
  src/translations/es.translations.json
  src/translations/fr.translations.json
  src/translations/nl.translations.json
  src/translations/sv.translations.json
Labels: bug

#5 feat: chatbot system option translation for all languages, translate …
  src/translations/ar.translations.json
  src/translations/de.translations.json
  src/translations/en.translations.json
  src/translations/es.translations.json
  src/translations/fr.translations.json
  src/translations/nl.translations.json
  src/translations/sv.translations.json
Labels: enhancement

#6 fix: translate checkbox separate for roulette and slots
  src/translations/ar.translations.json
  src/translations/de.translations.json
  src/translations/en.translations.json
  src/translations/es.translations.json
  src/translations/fr.translations.json
  src/translations/nl.translations.json
  src/translations/sv.translations.json
Labels: bug

#7 fix: the word save has different meaning depending on the context
  src/translations/ar.translations.json
  src/translations/de.translations.json
  src/translations/en.translations.json
  src/translations/es.translations.json
  src/translations/fr.translations.json
  src/translations/nl.translations.json
  src/translations/sv.translations.json
Labels: bug

#8 feat: add turkish language translation
  src/translations/ar.translations.json
  src/translations/de.translations.json
  src/translations/en.translations.json
  src/translations/es.translations.json
  src/translations/fr.translations.json
  src/translations/nl.translations.json
  src/translations/sv.translations.json
  src/translations/tr.translations.json
Labels: enhancement

#9 feat: translation for the conditions command
  src/translations/ar.translations.json
  src/translations/de.translations.json
  src/translations/en.translations.json
  src/translations/es.translations.json
  src/translations/fr.translations.json
  src/translations/nl.translations.json
  src/translations/sv.translations.json
  src/translations/tr.translations.json
Labels: enhancement

#10 fix: conditional command rewording
  src/translations/ar.translations.json
  src/translations/de.translations.json
  src/translations/en.translations.json
  src/translations/es.translations.json
  src/translations/fr.translations.json
  src/translations/nl.translations.json
  src/translations/sv.translations.json
  src/translations/tr.translations.json
Labels: bug
